### ISSUE TITLE
Create a roadmap

### ISSUE THREAD

**Issue by domthom21** [domthom21/eurocodedesign#1]
Wikis are not supported for Github Free.

The next step for the lib is @nc-hsu :
 - [x] Choose a licence: LGPL or MPL
 - [x] Design the library structure
 - [x] Create the git repo from cookiecutter-pypackage
 - [x] Collect information of the necessary norms for your application

**Comment by domthom21** [comment]
Not needed anymore as subject is transfered to Discussions
